### ISSUE TITLE
Can not build the solution with error 

### ISSUE THREAD

**Issue by chenxizhang** [microsoftgraph/botframework-csharp-excelbot-rest-sample#1]
The error is below

![untitled](https://cloud.githubusercontent.com/assets/1996954/19715714/a849fd58-9b89-11e6-81ab-7a6a5c9f9738.png)

**Comment by chenxizhang** [comment]
2>C:\Users\arechen\office365sample\botframework-csharp-excelbot-rest-sample\ExcelBot\Helpers\AuthHelper.cs(31,57,31,64): error CS0246: The type or namespace name 'Message' could not be found (are you missing a using directive or an assembly reference?)

**Comment by jakobpn** [comment]
Hi Chenxi Zhang, any chance that you have updated the Microsoft.Bot.Builder library to another version than 1.2.0? The code in this sample has not been upgraded to version 3 yet.
Jakob

**Comment by jakobpn** [comment]
Will go ahead and close the issue. Chenxi Zhang, let us know if you didn't get your issue resolved. Jakob
