### ISSUE TITLE
Some browsers result in error message when trying to access workbook

### ISSUE THREAD

**Issue by pvanaarde** [microsoftgraph/botframework-csharp-excelbot-rest-sample#3]
Hi,

I implemented this example and have a sample file called **Customer Data** on a generic company profile's OneDrive. When I use the bot through WebChat, I get different results in different browsers. In Chrome, it works as expected and I can interact with the workbook. When I try to use Edge however, I run into the following error message when trying to open the workbook: _Sorry, something went wrong when I tried to open the Customer Data workbook on your OneDrive for Business (String was not recognized as a valid DateTime.)_
Another user experiences the above error when using Chrome, even though he is using the same generic company login that I do.
Below screenshot shows the different responses that I experience. On the left is using Edge, and on the right is Chrome.
![capture](https://cloud.githubusercontent.com/assets/26129757/25259753/5ad9b60c-268b-11e7-8681-0e86b05f7584.PNG)

Any help would be greatly appreciated.

Thanks,
Pieter

**Comment by jakobpn** [comment]
Hi Peiter,

There was a recent update to https://github.com/microsoftgraph/uwp-csharp-excel-snippets-rest-sample related to parsing dates. Do you have the latest version of this code?

I would suggest that you attach the debugger and have it break on System.FormatException (String was not recognized as a valid DateTime) so that we can learn where the error is happening. 

Jakob

**Comment by jakobpn** [comment]
Hello, Peiter. Have you had a chance to do further debugging on this issue?

**Comment by pvanaarde** [comment]
Hi Jakob,

Apologies for my delayed response. I haven't debugged this further as we have built parts of the logic into a seperate bot that we are developing. At this stage, we haven't encountered this issue on this new bot, keeping in mind it only has some of the features provided in this sample.
As such I'll close this issue for now, and will reopen when we encounter it again.

Cheers,
Pieter
