### ISSUE TITLE
LUIS import fails

### ISSUE THREAD

**Issue by sjwaight** [microsoftgraph/botframework-csharp-excelbot-rest-sample#4]
The current ExceBot.json fails to import into LUIS with 'BadRequest': regex too complicated when any of the existing regex statements are present. When removing them the import runs fine.

**Comment by jakobpn** [comment]
I am wondering, if it is this regex that is causing the issue:

    {

      "name": "Name",

      "pattern": "[a-z_\\\\][\\w\\d\\._]*",

      "activated": true

    }

Try changing the pattern to: [a-z_][\w\d\._]*

**Comment by sjwaight** [comment]
I will try that, but in the meantime I removed all the regex expressions to import the json.
