### ISSUE TITLE
Target Excel Workbook is missing from sample

### ISSUE THREAD

**Issue by sjwaight** [microsoftgraph/botframework-csharp-excelbot-rest-sample#5]
The actual Excel Workbook used as the target for this sample application is not present in the solution, nor is it linked form the instructions.

**Comment by jakobpn** [comment]
That is correct. You will need to either create a new workbook on your OneDrive for Business or use a workbook that is already there.

**Comment by sjwaight** [comment]
Sure, already did that. Given the effort it is to get this running it would be good to include one. I will submit a PR with a sample one when I'm done preparing my demo.
